import { prisma } from "@/lib/prisma";
import { calculateNetPay, calculateEmployerPension } from "@/lib/finance-utils";
import { getActiveBandSet } from "@/lib/paye";
import { NextResponse } from "next/server";

/**
 * Monthly payroll/tax obligation cron — runs on the 27th of every month.
 *
 * Two jobs:
 * 1. For every active employee with no Payroll record for the current period yet
 *    (e.g. salary was paid manually via a Submission/Invoice instead of the
 *    Payroll module), auto-create a PENDING Payroll record so PAYE and Pension
 *    obligations are captured and surface on the Tax Dashboard as outstanding —
 *    regardless of how the actual disbursement was recorded.
 * 2. Any Payroll record still PENDING (salary not yet paid) or with outstanding
 *    PAYE for the current period or earlier is converted into an overdue
 *    AccountPayable, so it shows up on the Payables dashboard too.
 *
 * Idempotent — skips employees/records already covered. Protected by CRON_SECRET.
 */
export async function GET(req: Request) {
  const authHeader = req.headers.get("authorization");
  if (authHeader !== `Bearer ${process.env.CRON_SECRET}`) {
    return NextResponse.json({ error: "Unauthorised" }, { status: 401 });
  }

  try {
    const now = new Date();
    const currentPeriod = now.toISOString().slice(0, 7); // "YYYY-MM"
    const [periodYear, periodMonth] = currentPeriod.split("-").map(Number);
    const periodDate = new Date(periodYear, periodMonth - 1, 1);

    // System creator: first active CEO (cron has no session user)
    const systemUser = await prisma.user.findFirst({
      where: { role: "CEO", active: true },
      select: { id: true },
    });
    if (!systemUser) {
      return NextResponse.json({ error: "No active CEO found to attribute records to" }, { status: 500 });
    }

    // ── 1. Backfill missing PAYE/Pension records for the current period ──────
    const activeEmployees = await prisma.employee.findMany({ where: { active: true } });
    const existingForPeriod = await prisma.payroll.findMany({
      where: { period: currentPeriod },
      select: { employeeId: true },
    });
    const alreadyHasRecord = new Set(existingForPeriod.map((p) => p.employeeId));

    const bandSetInfo = await getActiveBandSet(periodDate);
    let obligationsCreated = 0;

    for (const employee of activeEmployees) {
      if (alreadyHasRecord.has(employee.id)) continue;

      const rate = employee.currency !== "MWK" ? (employee.salaryExchangeRate ?? 1) : 1;
      const calc = calculateNetPay(employee.grossSalary, employee.pensionRate, rate, {
        payeExempt:       employee.payeExempt,
        nssfApplicable:   employee.nssfApplicable,
        nssfEmployeeRate: employee.nssfEmployeeRate,
        nssfEmployerRate: employee.nssfEmployerRate,
        payeBands:        bandSetInfo?.bands,
      });
      const employerPensionMWK = calculateEmployerPension(calc.grossMWK, employee.pensionRate);

      await prisma.payroll.create({
        data: {
          employeeId:      employee.id,
          period:          currentPeriod,
          grossSalary:     employee.grossSalary,
          paye:            calc.payeMWK,
          pension:         calc.pension,
          pensionEmployer: employerPensionMWK,
          nssfEmployee:    calc.nssfEmployee,
          nssfEmployer:    calc.nssfEmployer,
          netPay:          calc.netPay,
          currency:        employee.currency,
          status:          "PENDING",
          notes:           "Auto-generated by monthly cron — captures PAYE/pension obligation; record actual payment separately.",
          payeBandSetId:    bandSetInfo?.id ?? null,
          payeBandSnapshot: bandSetInfo?.snapshot
            ? (bandSetInfo.snapshot as unknown as import("@prisma/client").Prisma.InputJsonValue)
            : undefined,
        },
      });
      obligationsCreated++;
    }

    // ── 2. Convert unpaid salaries / outstanding PAYE into payables ──────────
    const unpaidSalaries = await prisma.payroll.findMany({
      where: { status: "PENDING", period: { lte: currentPeriod }, deletedAt: null },
      include: { employee: { select: { name: true } } },
    });

    const outstandingPaye = await prisma.payroll.findMany({
      where: { payeStatus: "OUTSTANDING", period: { lte: currentPeriod }, deletedAt: null, paye: { gt: 0 } },
      include: { employee: { select: { name: true } } },
    });

    let salariesConverted = 0;
    let payeConverted = 0;

    for (const p of unpaidSalaries) {
      const already = await prisma.accountPayable.findFirst({
        where: { note: { contains: `Payroll ID: ${p.id} (salary)` } },
      });
      if (already) continue;

      await prisma.accountPayable.create({
        data: {
          description: `Unpaid Salary — ${p.employee.name} — ${p.period}`,
          vendor:      p.employee.name,
          amount:      p.netPay,
          currency:    p.currency,
          dueDate:     now,
          status:      "OVERDUE",
          budgetLine:  "Payroll",
          note:        `Auto-converted from unpaid payroll on the 27th (Payroll ID: ${p.id} (salary))`,
          createdBy:   systemUser.id,
        },
      });
      salariesConverted++;
    }

    for (const p of outstandingPaye) {
      const already = await prisma.accountPayable.findFirst({
        where: { note: { contains: `Payroll ID: ${p.id} (paye)` } },
      });
      if (already) continue;

      await prisma.accountPayable.create({
        data: {
          description: `Unpaid PAYE — ${p.employee.name} — ${p.period}`,
          vendor:      "Malawi Revenue Authority",
          amount:      p.paye,
          currency:    "MWK",
          dueDate:     now,
          status:      "OVERDUE",
          budgetLine:  "Tax",
          note:        `Auto-converted from outstanding PAYE on the 27th (Payroll ID: ${p.id} (paye))`,
          createdBy:   systemUser.id,
        },
      });
      payeConverted++;
    }

    return NextResponse.json({
      ok: true,
      period: currentPeriod,
      obligationsCreated,
      salariesConverted,
      payeConverted,
    });
  } catch (err) {
    console.error("[monthly-payables cron]", err);
    return NextResponse.json({ error: String(err) }, { status: 500 });
  }
}
